[package]
name = "willowd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rs9p = "0.13.0"
async-trait = "0.1"  # <--- Added this
log = "0.4"
env_logger = "0.11"
